export enum NotiSessionStorageKeys {
  ONE_SIGNAL_ID = 'ONE_SIGNAL_ID',
  ONE_SIGNAL_SUBSCRIPTION_ID = 'ONE_SIGNAL_SUBSCRIPTION_ID',
  NOTIFICATIONS_DATA = 'NOTIFICATIONS_DATA',
  KEY_ONE_SIGNAL_REGISTERED = 'KEY_ONE_SIGNAL_REGISTERED',
  KEY_NOTIFICATION_STATUS = 'KEY_NOTIFICATION_STATUS',
}
